### PR TITLE
Add support for #public-suffixed keys

### PR DESCRIPTION
**Pull request by papandreou**
... as suggested by @msiebuhr on #25.

### CODE REVIEW

**Comment by papandreou** [comment]
// cc @mwoc

**Comment by mwoc** [comment]
That works, +1 from me

**Comment by papandreou** [comment]
Thanks :)

**Comment by papandreou** [comment]
Damn, turns out this needs some more work in order to support `#public`-suffixed keys to override identically named keys in `#public` blocks, and vice versa.

"Luckily" the current behavior is that you'll get an error, so at least you won't end up with a mangled config.

Landed some failing tests on master.

**Pull request merged**
